import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { DarkModeSwitch } from "react-toggle-dark-mode";

export default function Home() {
  const [switchMode, setSwitchMode] = useState(true);

  const [isDarkMode, setDarkMode] = useState(true);

  const toggleDarkMode = (checked) => {
    setDarkMode(checked);
  };

  return (
    <>
      <Head>
        <title>resume by Yogesh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body style={{color: isDarkMode? "#fff":'#000', backgroundColor:isDarkMode? "#000":"#fff"}}>
        <div id="container--main">
          <section className="section-page">
            <p style={{fontSize:'15px'}}>Where to find me</p>
            <div id="socials--list">
              <a href="#" target="_blank">
                Linkedin
              </a>
              <a
                href="https://github.com/yogesh2104"
                target="_blank"
                rel="noreferrer"
              >
                Github
              </a>
              <a
                href="https://github.com/yogesh2104"
                target="_blank"
                rel="noreferrer"
              >
                Instagram
              </a>
              <a href="#" target="_blank">
                Download Resume
              </a>
            </div>
          </section>
          <section id="wrapper" className="section-page">
            <span id="icon" className="toggle">
              {" "}
              <DarkModeSwitch
                style={{ marginBottom: "2rem" }}
                checked={isDarkMode}
                onChange={toggleDarkMode}
                size={30}
              />
            </span>
            <div>
              <h1 id="user-name">Yogesh Singh</h1>
              <p id="bio">
                Software Engineer, React Developer & Python developer.
              </p>
              <p id="email">singhyogesh2104@gmail.com</p>
            </div>
             <Image
              id="profile-pic"
              src="/profile.svg"
              alt="Profile Pic"
              width={100}
              height={50}
              priority
            />
          </section>
          <section className="section-page">
            <h2>Skills & Qualifications</h2>
            <ul id="qualifications--list">
              <li>✔️ 1 Years experience with ReactJs development</li>
              <li>✔️ Experienced in API design In Django</li>
              <li>✔️ Extensive knowledge ReactJs,NextJS</li>
              <li>🎓 2022 MCA Pass Out with GPA: 8.89/10</li>
            </ul>
            <div className="line-break"></div>

          </section>
          <section className="section--page">
            <h2>Tech stack</h2>
            <div className="line-break"></div>
            <div className="line-break"></div>
            <div className="line-break"></div>
            <div style={{marginTop:20,marginBottom:15}} id="techstack">
              <div className="card">
                <span>Javascript</span>
              </div>
              <div className="card">
                <span>ReactJs</span>
              </div>
              <div className="card">
                <span>Python</span>
              </div>
              <div className="card">
                <span>Django</span>
              </div>
              <div className="card">
                <span>HTML,CSS,Tailwind CSS</span>
              </div>
              <div className="card">
                <span>GraphQL</span>
              </div>
              <div className="card">
                <span>MySQL</span>
              </div>
            </div>
            <div className="line-break"></div>
          </section>

          <section id="work-history-wrapper" className="section--page">
            <h2 style={{marginTop:10}}>Work History</h2>
            <div className="line-break"></div>
            <div className="line-break"></div>
            <div className="line-break"></div>
          </section>
          <section className="section--page">
            <h2 style={{marginTop:20}}>Projects & Accomplishments</h2>
            <div className="project">
                <span>🏆 </span>Analysis of Cryptographic Technique for Communication System(Research Paper)
            </div>
            <div className="project">
              <a>
                <span>🏆 </span>Built a Examination management system Collage Project
              </a>
            </div>
            <div className="project">
                <span>🏆 </span>CMS website Using Django Web Framework
            </div>
            <div className="project">
              <a>
                <span>🏆 </span>Vehicle-Showroom platform using PHP This is Collage group project 
              </a>
            </div>
          </section>
        </div>
      </body>
    </>
  );
}
